# -*- coding: utf-8 -*-
"""bibFuncoesHistograma

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-gPz6yq5ux7zuL_5OXFpg2KHWqzTM6eA
"""

def fazerHistograma(imagem, M, N):
    
    # importando as bibliotecas
    import numpy as np
    import matplotlib.pyplot as plt
    import cv2
    
    # definindo a matriz de zeros
    histograma = np.zeros((256), int)
    
    for l in range(M):
        for c in range(N):
            histograma[imagem[l,c]] = histograma[imagem[l,c]]+1
    
    return histograma